### ISSUE TITLE
requirements.txt for project

### ISSUE THREAD

**Issue by rmariusg** [mks0601/Face_detection#15]
Hi,
Even though you made this project around two years ago (at the moment of writing this request), could you write a requirements.txt for this project to help us who are still learning and reduce the back and forth time for finding all the necessary libraries?

Thank you very much,
Marius

**Comment by mks0601** [comment]
There is no much things to do before running this code if you use Ubuntu and TensorFlow. I think the only thing to consider is the version of TF becasue this project is implemented on the old version of Tensorflow. Is there anything makes you difficult to run this code?

**Comment by rmariusg** [comment]
I'm currently running with python3 and the latest TensorFlow that comes from installing it with pip. Still waiting for the 12-net to finish with the negatives. After I finish successfully, would you agree with me sending you some info on how to run it on Windows to attach it to the readme or wherever? :)

**Comment by mks0601** [comment]
Sorry, I haven`t used window for TF. You may find other useful post in the google.

**Comment by safaad** [comment]
Hi, I am trying to run _12net.py && 24-net && 48-net and I'm getting the error can't reshape array size
any ideas to solve it?

**Comment by rmariusg** [comment]
Hey,
I managed to run the code by moving it to a Ubuntu 18.04.1 virtual machine and using python2 with TensorFlow 1.10. After running train_12net, train_calib 12 and then trying to do a hard_neg_mining 24 it stops at around 127/828 (my neg files) and it says it just killed the process with no warning whatsoever. I tried debugging it, but couldn't figure it out. Do you have some pointers to give?

**Comment by mks0601** [comment]
Did you check the RAM status? Maybe the error comes from OOM.

**Comment by rmariusg** [comment]
Well, I have around 5 gigs or RAM. Do you believe it'd be enough?
To be mentioned: tensorflow runs only on CPU on the VM.

**Comment by rmariusg** [comment]
Another issue arose:

```
Traceback (most recent call last):
  File "/home/rmariusg/Downloads/cercetare/A-Convolutional-Neural-Network-Cascade-for-Face-Detection/hard_neg_mining.py", line 145, in <module>
    neg_db_12[iid,:] = util.img2array(cropped_img,param.img_size_12)
  File "/home/rmariusg/Downloads/cercetare/A-Convolutional-Neural-Network-Cascade-for-Face-Detection/util.py", line 14, in img2array
    if img.size[0] != param.img_size_12 or img.size[1] != param.img_size_12:
AttributeError: 'int' object has no attribute 'size'
```

I can't for the love of me figure out why the heck I get a box[5] of just 0. And only when I have an extremely low number of neg_train images...

**Comment by mks0601** [comment]
Solved? please ask me again if you meet any problems.
