### ISSUE TITLE
calib_12net accuracy

### ISSUE THREAD

**Issue by bk202** [mks0601/Face_detection#17]
Hi, I have reached a accuracy bottleneck of 61% for the 12 calibration net while attempting to train my own C-CNN. Can you please tell me if you have overcome that bottleneck or not, and if a low calibration net accuracy have any impact on the entire network? Thank you.

**Comment by ZZ94** [comment]
Hi, did you encounter the error (ValueError: cannot reshape array of size 619500 into shape (500,413,1)) when running the train12_net file?

**Comment by bk202** [comment]
@ZZ94 No, I was implementing the C-CNN in my own code, so I didn't encounter this issue.

**Comment by ZZ94** [comment]
@bk202 ok thank you
