### ISSUE TITLE
Can you give me your 'annot' file?

### ISSUE THREAD

**Issue by tengshaofeng** [mks0601/Face_detection#2]
dear mks0601,  i am so appreciate your work. I want to debug your code for learning. But i have images,but without 'annot' file. Can you give me your 'annot' file?

**Comment by mks0601** [comment]
Hi it`s been a long time i implemented and uploaded this work so that i removed it.. I used sqlite to parse the given sql annotations. it`s not hard so you can try yourself

**Comment by tengshaofeng** [comment]
i had done. Thanks for your advise

**Comment by ShuoYe2020** [comment]
Hi @tengshaofeng ,I'm a student studying CNN,I have the same problem as you,could you please tell me how to solve the problem that no 'annot' file in the project ,can you give me your 'annot' file?thanks a lot!

**Comment by tengshaofeng** [comment]
@Redemfre I used sqlite to parse the given sql annotations

**Comment by mks0601** [comment]
You have to run the data_parse.py in the dataGen folder. Please read the README.

**Comment by ShuoYe2020** [comment]
Thanks for your help ,i have solved this problem, now I have a new problem:
            ValueError: Shapes (2, 1) and () are incompatible
Does this problem have anything to do with the Tensorflow API?

**Comment by ShuoYe2020** [comment]
Dear @mks0601 @tengshaofeng ,I found the answer to the question, because the version of TF I used was different, so the changes needed to be made when defining tf.concat.
    However, then i was training 'train_24net.py', i met a tough problem,the following error occurred while running the program:     "ValueError :sample large than population".  
    The program is stuck at " neg_id = random.sample(xrange(len(neg_db_24)),param.neg_batch)",I looked at the parameters and found in 'data.py', when dim==24,
          'neg_db_12 = np.empty((0,param.img_size_12,param.img_size_12,param.input_channel),np.float32)
s.listdir(param.neg_dir + "neg_hard/24/") if f.startswith("12_") and f.endswith(".npy")]'
    The result of the statement execution is an empty array.so, all subsequent executions returned an empty array,such as :neg_file_list、 neg_db_24
    Did I make a serious mistake or think in the wrong direction? I appreciate your help, thank you very much!
